version = 0.1
[default.deploy.parameters]
stack_name = "api-gestor-pedidos"
resolve_s3 = true
s3_prefix = "api-gestor-pedidos"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "LayerLambdaAPI=\"arn:aws:lambda:us-east-1:527847838144:layer:lambda-api-v1:1\" S3Store=\"clarosv-store\" S3ImagenesFolder=\"tienda-pedidos/\""
